apiVersion: v1
kind: Service
metadata:
  name: statamic-app-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: statamic-app  # Must match the labels of the statamic-app pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80  # Bind to port 80 on the VM
  externalIPs:
  - 52.172.213.33  # The VM's public IP
