apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: kind-registry:5000/cms:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_URL
          value: "http://localhost"
        - name: PHP_MEMORY_LIMIT
          value: "512M"
        - name: PHP_UPLOAD_MAX_FILESIZE
          value: "10M"
        - name: PHP_POST_MAX_SIZE
          value: "10M"
