apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 4  # Running 4 replicas as required
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      initContainers:
      - name: copy-content
        image: busybox
        command: ['sh', '-c', 'cp -R /source/* /dest/ || true']
        volumeMounts:
        - name: host-content
          mountPath: /source
        - name: cms-content
          mountPath: /dest
      containers:
      - name: cms
        image: kind-registry:5000/cms:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: cms-content
      volumes:
      - name: host-content
        hostPath:
          path: /mnt/myproject
          type: Directory
      - name: cms-content
        emptyDir: {}
