apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
  labels:
    app: ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
        - name: ai-backend
          image: kind-registry:5000/ai-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 89
          env:
            - name: PORT
              value: "89"
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_SPEECH_KEY
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: AZURE_SPEECH_KEY
            - name: AZURE_SPEECH_REGION
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: AZURE_SPEECH_REGION
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: DB_PASSWORD
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: DB_SERVER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: azure-config
                  key: DB_NAME
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: ai-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ai-backend
spec:
  selector:
    app: ai-backend
  ports:
    - port: 89
      targetPort: 89
  type: ClusterIP
