services:
  ai-frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "91:91"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - ai-backend

  ai-backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "89:89"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=89
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_SQL_CONNECTION_STRING=${AZURE_SQL_CONNECTION_STRING}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
    restart: unless-stopped

networks:
  default:
    name: ai-network
