services:
  ai-frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "91:91"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://ai-backend:89/api
    depends_on:
      - ai-backend
    networks:
      - ai-network

  ai-backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "89:89"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
