services:
  ai-frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "91:91"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - ai-backend

  ai-backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "89:89"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=89
      - AZURE_STORAGE_CONNECTION_STRING=https://centralindia.api.cognitive.microsoft.com/
      - AZURE_SQL_CONNECTION_STRING=${AZURE_SQL_CONNECTION_STRING}
      - AZURE_SPEECH_KEY=896THn8b3fJwSq26scagN4CyhWS3FQUxDTnxNaPI3RHQdWTSWgcVJQQJ99BDACGhslBXJ3w3AAAYACOGQXEO
      - AZURE_SPEECH_REGION=centralindia
    restart: unless-stopped

networks:
  default:
    name: ai-network
