# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
      endpoint = ["http://registry:5000"]
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/andrei/STD_TEMA_2/cms/myproject
        containerPath: /mnt/myproject
    extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
      listenAddress: "0.0.0.0"
    - containerPort: 30090
      hostPort: 30090
      protocol: TCP
    - containerPort: 30091
      hostPort: 30091
      protocol: TCP
    - containerPort: 80
      hostPort: 80
      protocol: TCP
