apiVersion: v1
data:
  nginx.conf: "server {\n    listen 90;\n    server_name localhost;\n    root /usr/share/nginx/html;\n
    \   index index.html index.htm;\n    \n    location /ws {\n        proxy_pass
    http://chat-backend:88;\n        proxy_http_version 1.1;\n        proxy_set_header
    Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_set_header
    Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header
    X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_read_timeout 86400;\n
    \   }\n    \n    error_page 500 502 503 504 /50x.html;\n    location = /50x.html
    {\n        root /usr/share/nginx/html;\n    }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: chat-frontend-nginx-config
