apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "127.0.0.1" 
spec:
  selector:
    app: chat-frontend
  ports:
    - port: 90
      targetPort: 90
      nodePort: 30090
  type: NodePort
