apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  labels:
    app: chat-backend
spec:
  replicas: 4  
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: kind-registry:5000/chat-backend:latest
        ports:
        - containerPort: 88
        env:
        - name: PORT_WS
          value: "88"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/chatapp"
        - name: NODE_ENV
          value: "production"
