apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  labels:
    app: ai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
        - name: ai-frontend
          image: kind-registry:5000/ai-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 91
---
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
spec:
  selector:
    app: ai-frontend
  ports:
    - port: 91
      targetPort: 91
  type: ClusterIP
