apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  labels:
    app: ai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend    
    spec:
      containers:
      - name: ai-frontend
        image: kind-registry:5000/ai-frontend:latest
        ports:
        - containerPort: 91
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: ai-frontend-nginx-config
