apiVersion: v1
data:
  nginx.conf: "server {\n    listen 91;\n    server_name localhost;\n    \n    root
    /usr/share/nginx/html;\n    index index.html index.htm;\n    \n    location /
    {\n        try_files $uri $uri/ /index.html;\n    }\n    \n    # Proxy API requests
    to backend\n    location /api {\n        proxy_pass http://ai-backend:89;\n        proxy_http_version
    1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header
    Connection 'upgrade';\n        proxy_set_header Host $host;\n        proxy_set_header
    X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       proxy_cache_bypass $http_upgrade;\n    }\n    \n    error_page 500 502
    503 504 /50x.html;\n    location = /50x.html {\n        root /usr/share/nginx/html;\n
    \   }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ai-frontend-nginx-config
